import urllib.request
import json
import ssl
import os
from datetime import datetime

# REGION ID
THE_FORGE = "10000002"

# COMPREHENSIVE ITEM LIST FOR JITA DEMAND SCAN (T1 Focus)
SCANNED_ITEMS = {
    # Minerals
    "Tritanium": "34", "Pyerite": "35", "Mexallon": "36", "Isogen": "37", 
    "Nocxium": "38", "Zydrine": "39", "Megacyber": "40",
    # Fuel
    "Nitrogen Fuel Block": "4051", "Oxygen Fuel Block": "4247", 
    "Helium Fuel Block": "4312", "Hydrogen Fuel Block": "4246",
    # Ammo
    "Antimatter Charge M": "218", "Antimatter Charge S": "230", "Antimatter Charge L": "206",
    "Scourge Heavy Missile": "195", "Scourge Light Missile": "191", "Nova Heavy Missile": "193",
    "EMP S": "183", "EMP M": "177",
    # Drones
    "Warrior I": "2486", "Hobgoblin I": "2454", "Acolyte I": "2203", "Hornet I": "2470",
    # Modules
    "Damage Control I": "520", "1600mm Steel Plates I": "11299", 
    "Medium Shield Extender I": "380", "5MN Microwarpdrive I": "434",
    # Essentials
    "Nanite Repair Paste": "28668", "Cap Booster 400": "1121", "Cap Booster 800": "1122"
}

def fetch_tycoon_stats(type_id):
    url = f"https://evetycoon.com/api/v1/market/stats/{THE_FORGE}/{type_id}"
    ctx = ssl._create_unverified_context()
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'ShrimpBot-Volume-Stalker'})
        with urllib.request.urlopen(req, context=ctx) as r:
            return json.loads(r.read().decode())
    except: return {}

def format_vol(vol):
    if vol >= 1e9: return f"{vol/1e9:.1f}B"
    if vol >= 1e6: return f"{vol/1e6:.1f}M"
    if vol >= 1e3: return f"{vol/1e3:.1f}k"
    return str(int(vol))

def generate_report():
    print("Beginning Jita High-Demand Scan...")
    results = []
    tax = 0.036
    
    for name, tid in SCANNED_ITEMS.items():
        data = fetch_tycoon_stats(tid)
        s_price = float(data.get("minSell", 0))
        b_price = float(data.get("maxBuy", 0))
        s_vol = float(data.get("sellVolume", 0))
        
        if s_price > 0 and b_price > 0:
            # ROI: (Sell * (1-tax) / Buy) - 1
            spread = (((s_price * (1 - tax)) / b_price) - 1) * 100
            results.append({
                "name": name,
                "price": s_price,
                "vol": s_vol,
                "spread": spread
            })

    # Sort by Volume (Absolute units sold in 24h)
    results.sort(key=lambda x: x['vol'], reverse=True)
    top_vols = results[:10]

    # Sort by Profit (Spread) but requiring > 10,000 units volume to ignore "niche" items
    profit_candidates = [r for r in results if r['vol'] > 1000]
    profit_candidates.sort(key=lambda x: x['spread'], reverse=True)
    top_spreads = profit_candidates[:10]

    summary = "# 🛠️ Jita Manufacturing Analysis (High Demand)\n"
    summary += f"Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}\n\n"
    summary += "### 🛡️ Analysis Parameters\n"
    summary += "- **Region:** The Forge (Region-wide Jita stats).\n"
    summary += "- **Liquidity Check:** Volume based on 24h actual sell settlements.\n"
    summary += "- **Profit:** Realized net income assuming 3.6% fees.\n\n"

    summary += "## 🔥 Top 10 Jita High-Demand Items (Unit Volume)\n"
    summary += "These are the most liquid T1 items in Jita. Building these ensures instant sales.\n\n"
    summary += "| Item | Price (Sell) | Daily Volume | Net Spread |\n"
    summary += "| :--- | :--- | :--- | :--- |\n"
    for r in top_vols:
        summary += f"| **{r['name']}** | {r['price']:,.2f} | {format_vol(r['vol'])} | {r['spread']:.1f}% |\n"

    summary += "\n## 💎 Top 10 Liquid Profit Targets\n"
    summary += "Items with high volume (>1k/day) and the best manufacturing spreads.\n\n"
    summary += "| Item | Daily Volume | Net Spread | Recommendation |\n"
    summary += "| :--- | :--- | :--- | :--- |\n"
    for r in top_spreads:
        rec = "Strong Buy" if r['spread'] > 20 else "Stable"
        summary += f"| **{r['name']}** | {format_vol(r['vol'])} | **{r['spread']:.1f}%** | {rec} |\n"

    summary += "\n\n--- \n*Generated by the Shrimp Market Bot via EVE Tycoon API.* 🍤"
    return summary

if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target_path = os.path.join(base_dir, "JITA_MFG_ANALYSIS.md")
    with open(target_path, "w") as f: f.write(generate_report())
    print("Jita Manufacturing Analysis Overhauled.")
