import urllib.request
import json
import ssl
import os
from datetime import datetime

# EVE Hub Station/Structure IDs
JITA_IV_4 = "60003760"
AMARR_VIII = "60008494"
DODIXIE_IX = "60011866"

# Expanded list of High Sec ores (Belt + Anomaly/Escalation spawn)
TARGET_TYPES = {
    "Compressed Veldspar": "28432",
    "Compressed Scordite": "28429",
    "Compressed Pyroxeres": "28422",
    "Compressed Plagioclase": "28421",
    "Compressed Omber": "28399",
    "Compressed Kernite": "28394",
    "Compressed Jaspet": "28404",
    "Compressed Hemorphite": "28407",
    "Compressed Hedbergite": "28410",
    "Compressed Gneiss": "28416",
    "Compressed Dark Ochre": "28415",
    "Compressed Crokite": "28418"
}

# Manufacturing targets (High turnover T1 items)
MFG_TYPES = {
    "Venture": "32880",
    "Hobgoblin I": "2454",
    "Caldari Fuel Block": "4051",
    "Antimatter Charge S": "230",
    "Scourge Heavy Missile": "195",
    "Iteron Mark V": "657",
    "Badger": "649"
}

def fetch_prices(station_id, type_ids):
    ids_str = ",".join(type_ids)
    url = f"https://market.fuzzwork.co.uk/aggregates/?station={station_id}&types={ids_str}"
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    try:
        with urllib.request.urlopen(url, context=ctx) as response:
            return json.loads(response.read().decode())
    except Exception as e:
        print(f"Error fetching data for station {station_id}: {e}")
        return {}

def calculate_spreads():
    types = list(TARGET_TYPES.values())
    jita = fetch_prices(JITA_IV_4, types)
    amarr = fetch_prices(AMARR_VIII, types)
    dodi = fetch_prices(DODIXIE_IX, types)
    
    summary = "# 🚀 EVE Arbitrage Weekly Briefing\n"
    summary += f"Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}\n\n"
    summary += "This report is automatically generated and tracks compressed ore spreads between regional hubs and Jita.\n\n"
    summary += "## 📈 High Sec Market Spreads\n"
    summary += "| Ore Type | Hub | Local Price | Jita Spread % |\n"
    summary += "| :--- | :--- | :--- | :--- |\n"
    
    found_any = False
    # Sort alphabetically for better reading
    sorted_names = sorted(TARGET_TYPES.items())
    
    for name, tid in sorted_names:
        jita_info = jita.get(tid, {}).get("sell", {})
        jita_price = float(jita_info.get("min", 0))
        
        hub_data = [("Amarr", amarr), ("Dodixie", dodi)]
        
        for hub_name, hub_json in hub_data:
            price_info = hub_json.get(tid, {}).get("sell", {})
            price = float(price_info.get("min", 0))
            if jita_price > 0 and price > 0:
                spread = ((jita_price - price) / price) * 100
                # Highlight spreads over 10%
                spread_text = f"**{spread:.1f}%**" if spread >= 10.0 else f"{spread:.1f}%"
                summary += f"| {name} | {hub_name} | {price:,.2f} | {spread_text} |\n"
                found_any = True

    if not found_any:
        summary += "| No significant spreads found for high sec ores today. | | | |\n"

    # Add Manufacturing Spotlight
    summary += "\n## 🛠️ Manufacturing Spotlight (Jita Demand)\n"
    summary += "Target items for T1 manufacturing based on high turnover and liquidity.\n\n"
    summary += "| Item | Jita Sell | Jita Buy | Spread |\n"
    summary += "| :--- | :--- | :--- | :--- |\n"
    
    mfg_ids = list(MFG_TYPES.values())
    jita_mfg = fetch_prices(JITA_IV_4, mfg_ids)
    
    for name, tid in sorted(MFG_TYPES.items()):
        item_info = jita_mfg.get(tid, {})
        sell = float(item_info.get("sell", {}).get("min", 0))
        buy = float(item_info.get("buy", {}).get("max", 0))
        
        if sell > 0 and buy > 0:
            spread = ((sell - buy) / buy) * 100
            summary += f"| {name} | {sell:,.2f} | {buy:,.2f} | {spread:.1f}% |\n"

    summary += "\n\n--- \n*Generated by the Shrimp Market Bot. Includes belt ores and anomaly/escalation types.* 🍤"
    return summary

if __name__ == "__main__":
    report = calculate_spreads()
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    report_path = os.path.join(repo_root, "MARKET_DATA.md")
    
    with open(report_path, "w") as f:
        f.write(report)
    
    print(f"Analysis complete. Full report synced to {report_path}")
    print(report)
