import urllib.request
import json
import ssl
from datetime import datetime

# EVE Hub Station/Structure IDs
JITA_IV_4 = "60003760"
AMARR_VIII = "60008494"
DODIXIE_IX = "60011866"

TARGET_TYPES = {
    "Compressed Veldspar": "28432",
    "Compressed Pyroxeres": "28422",
    "Compressed Kernite": "28394",
    "Compressed Omber": "28399"
}

def fetch_prices(station_id, type_ids):
    ids_str = ",".join(type_ids)
    url = f"https://market.fuzzwork.co.uk/aggregates/?station={station_id}&types={ids_str}"
    
    # Bypass SSL verification for internal utility script
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    
    try:
        with urllib.request.urlopen(url, context=ctx) as response:
            return json.loads(response.read().decode())
    except Exception as e:
        print(f"Error fetching data for station {station_id}: {e}")
        return {}

def calculate_spreads():
    types = list(TARGET_TYPES.values())
    
    jita = fetch_prices(JITA_IV_4, types)
    amarr = fetch_prices(AMARR_VIII, types)
    dodi = fetch_prices(DODIXIE_IX, types)
    
    summary = "# 🚀 EVE Arbitrage Weekly Briefing\n"
    summary += f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
    summary += "| Item | Hub | Price | Jita Spread % |\n"
    summary += "| :--- | :--- | :--- | :--- |\n"
    
    found_any = False
    for name, tid in TARGET_TYPES.items():
        jita_info = jita.get(tid, {}).get("sell", {})
        jita_price = float(jita_info.get("min", 0))
        
        hub_data = [("Amarr", amarr), ("Dodixie", dodi)]
        
        for hub_name, hub_json in hub_data:
            price_info = hub_json.get(tid, {}).get("sell", {})
            price = float(price_info.get("min", 0))
            if jita_price > 0 and price > 0:
                spread = ((jita_price - price) / price) * 100
                summary += f"| {name} | {hub_name} | {price:,.2f} | **{spread:.1f}%** |\n"
                found_any = True

    if not found_any:
        summary += "| No significant spreads found today. | | | |\n"

    summary += "\n\n🍤 *Generated by shrimp. Haul safe!*"
    return summary

if __name__ == "__main__":
    print(calculate_spreads())
